<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BusinessTypeSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'business_type'              => 'Freight Forwarder',
                'reg_type'                   => 'Company',
                'ledger'                     => 1,
                'haulier'                    => 0,
                'lpk_license_no'             => 1,
                'lpk_license_no_optional'    => 0,
                'lpk_ancillary_contractor'   => 0,
                'customs_license_no'         => 1,
                'sst_reg_no'                 => 1,
                'business_vol'               => 1,
                'trade_ref_no'               => 1,
                'bank_info'                  => 1,
                'operator_code'              => 0,
                'copy_board_director_ic'     => 1,
                'apad_certificate_no'        => 0,
                'license_expiry_date'        => 1,
                'warehouse_info'             => 0,
                'nature_of_business'         => 1,
                'pli'                        => 1,
                'status'                     => 'Active',
            ],
            [
                'business_type'              => 'Haulier',
                'reg_type'                   => 'Company',
                'ledger'                     => 1,
                'haulier'                    => 1,
                'lpk_license_no'             => 1,
                'lpk_license_no_optional'    => 0,
                'lpk_ancillary_contractor'   => 0,
                'customs_license_no'         => 0,
                'sst_reg_no'                 => 1,
                'business_vol'               => 1,
                'trade_ref_no'               => 1,
                'bank_info'                  => 1,
                'operator_code'              => 1,
                'copy_board_director_ic'     => 1,
                'apad_certificate_no'        => 1,
                'license_expiry_date'        => 1,
                'warehouse_info'             => 0,
                'nature_of_business'         => 1,
                'pli'                        => 1,
                'status'                     => 'Active',
            ],
            [
                'business_type'              => 'Warehouse Operator',
                'reg_type'                   => 'Company',
                'ledger'                     => 1,
                'haulier'                    => 0,
                'lpk_license_no'             => 0,
                'lpk_license_no_optional'    => 1,
                'lpk_ancillary_contractor'   => 0,
                'customs_license_no'         => 0,
                'sst_reg_no'                 => 1,
                'business_vol'               => 1,
                'trade_ref_no'               => 1,
                'bank_info'                  => 1,
                'operator_code'              => 0,
                'copy_board_director_ic'     => 1,
                'apad_certificate_no'        => 0,
                'license_expiry_date'        => 0,
                'warehouse_info'             => 1,
                'nature_of_business'         => 1,
                'pli'                        => 0,
                'status'                     => 'Active',
            ],
            [
                'business_type'              => 'Customs Agent',
                'reg_type'                   => 'Company',
                'ledger'                     => 1,
                'haulier'                    => 0,
                'lpk_license_no'             => 0,
                'lpk_license_no_optional'    => 0,
                'lpk_ancillary_contractor'   => 0,
                'customs_license_no'         => 1,
                'sst_reg_no'                 => 1,
                'business_vol'               => 1,
                'trade_ref_no'               => 1,
                'bank_info'                  => 1,
                'operator_code'              => 0,
                'copy_board_director_ic'     => 1,
                'apad_certificate_no'        => 0,
                'license_expiry_date'        => 1,
                'warehouse_info'             => 0,
                'nature_of_business'         => 1,
                'pli'                        => 0,
                'status'                     => 'Active',
            ],
            [
                'business_type'              => 'Ancillary Contractor',
                'reg_type'                   => 'Company',
                'ledger'                     => 0,
                'haulier'                    => 0,
                'lpk_license_no'             => 0,
                'lpk_license_no_optional'    => 0,
                'lpk_ancillary_contractor'   => 1,
                'customs_license_no'         => 0,
                'sst_reg_no'                 => 0,
                'business_vol'               => 0,
                'trade_ref_no'               => 0,
                'bank_info'                  => 1,
                'operator_code'              => 0,
                'copy_board_director_ic'     => 1,
                'apad_certificate_no'        => 0,
                'license_expiry_date'        => 0,
                'warehouse_info'             => 0,
                'nature_of_business'         => 1,
                'pli'                        => 0,
                'status'                     => 'Active',
            ],
            [
                'business_type'              => 'Sole Proprietor',
                'reg_type'                   => 'Individual',
                'ledger'                     => 1,
                'haulier'                    => 0,
                'lpk_license_no'             => 0,
                'lpk_license_no_optional'    => 1,
                'lpk_ancillary_contractor'   => 0,
                'customs_license_no'         => 0,
                'sst_reg_no'                 => 0,
                'business_vol'               => 1,
                'trade_ref_no'               => 0,
                'bank_info'                  => 1,
                'operator_code'              => 0,
                'copy_board_director_ic'     => 1,
                'apad_certificate_no'        => 0,
                'license_expiry_date'        => 0,
                'warehouse_info'             => 0,
                'nature_of_business'         => 1,
                'pli'                        => 0,
                'status'                     => 'Inactive',
            ],
        ];

        $this->db->table('businesstype')->insertBatch($data);
    }
}